spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://??:3306/ilou
    #url: jdbc:mysql://localhost:3306/ilou
    username: root
    password: ??
    #password: ??
  application:
    name: ilou
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  # redis 配置
  redis:
    port: 6379
    host: ??
    #host: localhost
    database: 0
    password: ??
server:
  port: 8080
  servlet:
    context-path: /api
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
knife4j:
  enable: true
  openapi:
    title: ilou后端api文档
    description: ilou后端api文档
    email: xiaoymin@foxmail.com
    concat: yinan
    url: https://docs.xiaominfo.com
    version: v4.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      test1:
        group-name: 分组名称
        api-rule: package
        api-rule-resources:
          - com.yinan.iloubackend.controller
          - com.yinan.iloubackend.controller
qiniu:
  accessKey: ??
  secretKey: ??
  # 对象储存
  bucket: ?? # 空间名称
  zone: ?? # 存储区域
  domain: ?? # 访问域名